%%% This file was automatically generated by snmpc_mib_to_hrl version 4.22.1
%%% Date: 27-Oct-2012::16:02:47
-ifndef('DHT-MIB').
-define('DHT-MIB', true).

%% Oids

-define(dht, [1,3,6,1,4,1,40750,1,1,1]).

-define(dhtArray, [1,3,6,1,4,1,40750,1,1,1,1]).

-define(dhtArrayEntry, [1,3,6,1,4,1,40750,1,1,1,1,1]).
-define(arrayIndex, 1).
-define(value, 2).
-define(dhtStatus2, 3).

-define(dhtTable, [1,3,6,1,4,1,40750,1,1,1,2]).

-define(dhtEntry, [1,3,6,1,4,1,40750,1,1,1,2,1]).
-define(dhtIndex, 1).
-define(handoffTimeouts, 2).
-define(nodeGetsTotal, 3).
-define(nodePutsTotal, 4).
-define(cpuAvg15, 5).
-define(nodeGetFsmTimeMedian, 6).
-define(nodePutFsmTimeMedian, 7).
-define(dhtStatus, 8).


%% Range values


%% Enum definitions from dhtStatus2
-define(dhtStatus2_destroy, 6).
-define(dhtStatus2_createAndWait, 5).
-define(dhtStatus2_createAndGo, 4).
-define(dhtStatus2_notReady, 3).
-define(dhtStatus2_notInService, 2).
-define(dhtStatus2_active, 1).

%% Enum definitions from dhtStatus
-define(dhtStatus_destroy, 6).
-define(dhtStatus_createAndWait, 5).
-define(dhtStatus_createAndGo, 4).
-define(dhtStatus_notReady, 3).
-define(dhtStatus_notInService, 2).
-define(dhtStatus_active, 1).

%% Default values

-endif.
