%%% This file was automatically generated by snmpc_mib_to_hrl version 4.22.1
%%% Date: 27-Oct-2012::16:02:40
-ifndef('SYNRC-REG').
-define('SYNRC-REG', true).

%% Oids

-define(synrc, [1,3,6,1,4,1,40750]).

-define(kakaranet, [1,3,6,1,4,1,40750,1]).

-define(kakaSquares, [1,3,6,1,4,1,40750,1,1]).


%% Range values


%% Default values

-endif.
